apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: blog-ghost
spec:
  replicas: 1
  strategy:
    type: Recreate # because PVC is ReadWriteOnce and if we have more than one replica, it will fail
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      terminationGracePeriodSeconds: 30 # 30 seconds to allow for proper shutdown
      securityContext:
        fsGroup: 1000 # required for Ghost to write to the content directory
      # first sidecar container to ensure proper permissions on the content directory
      initContainers:
        - name: volume-permissions
          image: busybox:1.36
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          command:
            - sh
            - -c
            - |
              mkdir -p /var/lib/ghost/content
              chown -R 1000:1000 /var/lib/ghost/content
          volumeMounts:
            - name: ghost-content
              mountPath: /var/lib/ghost/content
      # second sidecar container to wait for MySQL to be ready mysql-0.mysql.ghost.svc.cluster.local which is the headless service name
        - name: wait-for-mysql
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for MySQL..."
              until nc -z mysql-0.mysql.blog-ghost.svc.cluster.local 3306; do
                sleep 2
              done
              echo "MySQL is up."
      # main container
      containers:
        - name: ghost
          image: ghost:6.13.2-alpine
          ports:
            - name: http
              containerPort: 2368
          env:
            - name: NODE_ENV
              value: "production"
            - name: url
              value: "https://kblog.cloudycode.dev"

            - name: database__client
              value: "mysql"
            - name: database__connection__host
              value: "mysql-0.mysql.blog-ghost.svc.cluster.local" # headless service name
            - name: database__connection__user
              valueFrom:
                secretKeyRef:
                  name: ghost-secrets
                  key: mysql-user
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: ghost-secrets
                  key: mysql-password
            - name: database__connection__database
              valueFrom:
                secretKeyRef:
                  name: ghost-secrets
                  key: mysql-database

            - name: admin__email
              valueFrom:
                secretKeyRef:
                  name: ghost-secrets
                  key: ghost-admin-email
            - name: admin__user
              valueFrom:
                secretKeyRef:
                  name: ghost-secrets
                  key: ghost-admin-user
            - name: admin__password
              valueFrom:
                secretKeyRef:
                  name: ghost-secrets
                  key: ghost-admin-password

          volumeMounts:
            - name: ghost-content
              mountPath: /var/lib/ghost/content

          startupProbe:
            httpGet:
              path: /
              port: 2368
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: https
            failureThreshold: 30
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /
              port: 2368
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: https
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 2368
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: https
            initialDelaySeconds: 60
            periodSeconds: 10

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
      volumes:
        - name: ghost-content
          persistentVolumeClaim:
            claimName: ghost-content
