apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghost
  namespace: blog-ghost
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-ingress-class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: blog-ghost-https-redirect@kubernetescrd,blog-ghost-security-headers@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - kblog.cloudycode.dev
      secretName: kblog-cloudycode-dev-tls
  rules:
    - host: kblog.cloudycode.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ghost
                port:
                  number: 80
